// Retained only to resume existing local attempts; never scheduled for new rounds.
import { LANDSCAPE_ASPECT, type LandscapeDream, type LandscapeEdit } from '../v2/landscapeCollection.ts'
import type { HolidayId } from './holidayCalendar.ts'

export interface HolidayDream extends LandscapeDream {
  readonly holiday: HolidayId
  readonly occasion: string
  readonly verse: readonly [string, string]
}

// Coordinates use the compositor's 1672 × 941 artboard, not screen pixels.
function edit(id: string, label: string, difficulty: LandscapeEdit['difficulty'], [x, y, width, height]: readonly [number, number, number, number]): LandscapeEdit {
  return { id, label, difficulty, box: { left: x / 1672, top: y / 941, width: width / 1672, height: height / 941 }, edgeFade: 2 }
}

export const legacyHolidayDreams: readonly HolidayDream[] = [
  {
    id: 'holiday-halloween', holiday: 'halloween', occasion: 'Halloween',
    title: 'The Lantern Ferry',
    original: '/artwork/v3/holidays/halloween-original.png',
    altered: '/artwork/v3/holidays/halloween-altered-source.png',
    aspectRatio: LANDSCAPE_ASPECT,
    verse: ['A pumpkin ferry slips from sight,', 'And little things change boats tonight.'],
    edits: [
      edit('moon', 'The golden moon turns icy blue.', 'Easy', [180, 14, 228, 218]),
      edit('lantern', 'The lantern’s star becomes a crescent.', 'Medium', [1472, 408, 83, 92]),
      edit('clasp', 'The cat’s crescent clasp becomes a star.', 'Hard', [680, 365, 44, 43]),
      edit('paddle', 'The paddle loses its lower hole.', 'Very hard', [816, 673, 35, 42]),
      edit('candy', 'The candy corn loses its orange stripe.', 'Dreamlike', [515, 367, 44, 53]),
    ],
  },
  {
    id: 'holiday-thanksgiving', holiday: 'thanksgiving', occasion: 'Thanksgiving',
    title: 'A Feast Upon a Falling Leaf',
    original: '/artwork/v3/holidays/thanksgiving-original.png',
    altered: '/artwork/v3/holidays/thanksgiving-altered-source.png',
    aspectRatio: LANDSCAPE_ASPECT,
    verse: ['The harvest table drifts through gold,', 'With little changes left untold.'],
    edits: [
      edit('pie', 'The pie’s cream star becomes a heart.', 'Easy', [510, 372, 105, 58]),
      edit('handle', 'The teapot loses its tall top handle.', 'Medium', [677, 257, 118, 86]),
      edit('pear', 'The pear loses its left leaf.', 'Hard', [938, 329, 54, 44]),
      edit('napkin', 'The napkin loses its middle diamond.', 'Very hard', [964, 550, 38, 45]),
      edit('seal', 'The envelope’s seal is stamped with a heart.', 'Dreamlike', [1532, 110, 38, 36]),
    ],
  },
  {
    id: 'holiday-christmas', holiday: 'christmas', occasion: 'Christmas',
    title: 'The Keeper of Snow',
    original: '/artwork/v3/holidays/christmas-original.png',
    altered: '/artwork/v3/holidays/christmas-altered-source.png',
    aspectRatio: LANDSCAPE_ASPECT,
    verse: ['A winter workshop glows below;', 'What changed beneath the hush of snow?'],
    edits: [
      edit('topper', 'The tree’s star becomes a crescent.', 'Easy', [194, 30, 155, 156]),
      edit('ribbon', 'The gift’s green ribbon turns cranberry red.', 'Medium', [1300, 418, 249, 308]),
      edit('window', 'The round attic window loses its horizontal bar.', 'Hard', [903, 418, 43, 31]),
      edit('stocking', 'The stocking’s cream heel turns red.', 'Very hard', [21, 818, 85, 94]),
      edit('bell', 'The bell’s crossed slit becomes a single slit.', 'Dreamlike', [1418, 81, 56, 53]),
    ],
  },
  {
    id: 'holiday-valentines', holiday: 'valentines', occasion: "Valentine’s Day",
    title: "Letters on the Rose Canal",
    original: '/artwork/v3/holidays/valentines-original.png',
    altered: '/artwork/v3/holidays/valentines-altered-source.png',
    aspectRatio: LANDSCAPE_ASPECT,
    verse: ["Where folded letters softly flow,","Small secrets change in sunset’s glow."],
    edits: [
      edit("ribbon", "The swan’s crimson ribbon turns teal.", "Easy", [651,533,139,198]),
      edit("mailbox", "The mailbox’s heart opening becomes round.", "Medium", [226,391,75,88]),
      edit("handle", "The pink teacup loses its handle.", "Hard", [1525,704,112,124]),
      edit("lantern", "The lantern loses its middle gold heart.", "Very hard", [893,151,38,38]),
      edit("seal", "The envelope’s blue heart seal becomes a star.", "Dreamlike", [851,537,38,39]),
    ],
  },
  {
    id: 'holiday-st-patricks', holiday: 'st-patricks', occasion: "St. Patrick’s Day",
    title: "The Well of Wandering Luck",
    original: '/artwork/v3/holidays/st-patricks-original.png',
    altered: '/artwork/v3/holidays/st-patricks-altered-source.png',
    aspectRatio: LANDSCAPE_ASPECT,
    verse: ["By wishing wells the day turns green;","A second glance reshapes the scene."],
    edits: [
      edit("clover", "The pot’s shamrock gains a fourth leaf.", "Easy", [191,538,158,168]),
      edit("jewel", "The well’s blue jewel turns amber.", "Medium", [1449,151,58,64]),
      edit("band", "The bucket loses its middle brass band.", "Hard", [1425,668,193,49]),
      edit("buckle", "The otter’s square buckle becomes round.", "Very hard", [585,520,64,62]),
      edit("shell", "The snail’s shell loses its dark spiral.", "Dreamlike", [1380,750,94,85]),
    ],
  },
  {
    id: 'holiday-independence', holiday: 'independence', occasion: "Independence Day",
    title: "The Harbor That Bloomed",
    original: '/artwork/v3/holidays/independence-original.png',
    altered: '/artwork/v3/holidays/independence-altered-source.png',
    aspectRatio: LANDSCAPE_ASPECT,
    verse: ["Bright blossoms burst across the bay;","Look twice—small wonders slip away."],
    edits: [
      edit("sail", "The sail’s star becomes a crescent.", "Easy", [1043,162,196,202]),
      edit("lens", "The telescope’s blue lens turns rose-pink.", "Medium", [375,279,74,101]),
      edit("scarf", "The mouse’s red neckerchief turns teal.", "Hard", [899,477,142,61]),
      edit("handle", "The pitcher loses its loop handle.", "Very hard", [1546,558,125,211]),
      edit("sugar", "The biscuit loses its blue sugar dot.", "Dreamlike", [601,808,29,25]),
    ],
  },
  {
    id: 'holiday-new-years', holiday: 'new-years', occasion: "New Year’s Day",
    title: "The Door to Tomorrow",
    original: '/artwork/v3/holidays/new-years-original.png',
    altered: '/artwork/v3/holidays/new-years-altered-source.png',
    aspectRatio: LANDSCAPE_ASPECT,
    verse: ["A dawn-lit doorway opens wide;","Small changes sail in on the tide."],
    edits: [
      edit("sail", "The little boat’s blue sail turns coral.", "Easy", [751,410,204,232]),
      edit("key", "The key’s star-shaped bow becomes a heart.", "Medium", [891,244,91,95]),
      edit("bell", "The clock loses its right bell.", "Hard", [1552,484,99,82]),
      edit("stripe", "The jug loses its upper teal stripe.", "Very hard", [25,540,260,81]),
      edit("seal", "The paper boat’s red seal turns blue.", "Dreamlike", [514,811,67,71]),
    ],
  },
  {
    id: 'holiday-new-years-eve', holiday: 'new-years-eve', occasion: "New Year’s Eve",
    title: "The Whale at Midnight",
    original: '/artwork/v3/holidays/new-years-eve-original.png',
    altered: '/artwork/v3/holidays/new-years-eve-altered-source.png',
    aspectRatio: LANDSCAPE_ASPECT,
    verse: ["A rooftop whale drifts out of sight;","The year turns over—what changed tonight?"],
    edits: [
      edit("moon", "The golden crescent turns silver.", "Easy", [134,13,203,224]),
      edit("ribbon", "The candle’s purple bow turns teal.", "Medium", [0,580,335,361]),
      edit("watch", "The watch’s crescent engraving becomes a star.", "Hard", [397,649,144,137]),
      edit("bow", "The owl’s green bow turns red.", "Very hard", [1113,652,134,83]),
      edit("diamond", "The hat loses its middle diamond.", "Dreamlike", [1458,674,63,77]),
    ],
  },
  {
    id: 'holiday-easter', holiday: 'easter', occasion: "Easter",
    title: "The Garden Inside an Egg",
    original: '/artwork/v3/holidays/easter-original.png',
    altered: '/artwork/v3/holidays/easter-altered-source.png',
    aspectRatio: LANDSCAPE_ASPECT,
    verse: ["Where painted shells bloom in the dew,","The garden wakes a little new."],
    edits: [
      edit("zigzag", "The giant egg’s gold zigzag turns teal.", "Easy", [0,261,459,259]),
      edit("dot", "The pink egg loses its middle blue dot.", "Medium", [289,731,95,94]),
      edit("spout", "The watering can’s round sprinkler face becomes square.", "Hard", [1295,481,175,155]),
      edit("wing", "The butterfly loses its lower orange spot.", "Very hard", [1522,123,67,68]),
      edit("button", "The vest button has two holes instead of four.", "Dreamlike", [635,428,53,58]),
    ],
  },
  {
    id: 'holiday-mothers', holiday: 'mothers', occasion: "Mother’s Day",
    title: "The Nest That Held the Sky",
    original: '/artwork/v3/holidays/mothers-original.png',
    altered: '/artwork/v3/holidays/mothers-altered-source.png',
    aspectRatio: LANDSCAPE_ASPECT,
    verse: ["A cradle floats where cloud paths bend;","Small wonders shift before day’s end."],
    edits: [
      edit("flower", "The deer’s coral flower turns blue.", "Easy", [758,147,104,115]),
      edit("finial", "The teapot’s heart finial becomes a crescent.", "Medium", [165,283,82,79]),
      edit("apple", "The basket’s green apple turns red.", "Hard", [1458,491,139,120]),
      edit("cushion", "The cushion loses its middle star.", "Very hard", [431,736,58,63]),
      edit("keyhole", "The music box’s keyhole becomes a heart.", "Dreamlike", [1313,761,51,52]),
    ],
  },
  {
    id: 'holiday-fathers', holiday: 'fathers', occasion: "Father’s Day",
    title: "A Sail for the Sky",
    original: '/artwork/v3/holidays/fathers-original.png',
    altered: '/artwork/v3/holidays/fathers-altered-source.png',
    aspectRatio: LANDSCAPE_ASPECT,
    verse: ["A little sail takes wing today;","Familiar things have slipped away."],
    edits: [
      edit("sail", "The yellow sail turns teal.", "Easy", [837,106,303,340]),
      edit("scarf", "The cub’s purple scarf turns rust-red.", "Medium", [1040,512,282,207]),
      edit("compass", "The compass lid’s star becomes a crescent.", "Hard", [303,671,118,128]),
      edit("latch", "The toolbox loses its right brass latch.", "Very hard", [225,563,59,116]),
      edit("handle", "The mug’s square handle becomes round.", "Dreamlike", [1515,658,93,123]),
    ],
  },
  {
    id: 'holiday-mlk', holiday: 'mlk', occasion: "Martin Luther King Jr. Day",
    title: "A Bridge for Every Dream",
    original: '/artwork/v3/holidays/mlk-original.png',
    altered: '/artwork/v3/holidays/mlk-altered-source.png',
    aspectRatio: LANDSCAPE_ASPECT,
    verse: ["Where lanterns cross a bridge of light,","The dreaming world shifts out of sight."],
    edits: [
      edit("ribbon", "The bridge’s front blue bow turns coral.", "Easy", [390,430,377,324]),
      edit("lantern", "The rabbit’s lantern heart becomes a star.", "Medium", [244,602,85,108]),
      edit("planter", "The planter’s star becomes a crescent.", "Hard", [1525,719,113,110]),
      edit("bookmark", "The book’s crimson bookmark turns teal.", "Very hard", [378,736,128,166]),
      edit("leaf", "The dove’s twig loses its lower-right leaf.", "Dreamlike", [558,156,58,49]),
    ],
  },
  {
    id: 'holiday-presidents', holiday: 'presidents', occasion: "Presidents’ Day",
    title: "The Library Above the Clouds",
    original: '/artwork/v3/holidays/presidents-original.png',
    altered: '/artwork/v3/holidays/presidents-altered-source.png',
    aspectRatio: LANDSCAPE_ASPECT,
    verse: ["Where storybook stairways climb the air,","Look twice—was that detail always there?"],
    edits: [
      edit("quill", "The golden quill turns silver.", "Easy", [4,264,254,381]),
      edit("leaf", "The medallion’s oak leaf becomes a maple leaf.", "Medium", [896,95,130,145]),
      edit("bow", "The parchment’s blue bow turns burgundy.", "Hard", [773,702,283,193]),
      edit("button", "The owl’s vest loses its middle button.", "Very hard", [581,436,49,48]),
      edit("plate", "The chest’s star-shaped keyhole plate becomes round.", "Dreamlike", [1360,612,111,125]),
    ],
  },
  {
    id: 'holiday-memorial', holiday: 'memorial', occasion: "Memorial Day",
    title: "The Garden of Quiet Lanterns",
    original: '/artwork/v3/holidays/memorial-original.png',
    altered: '/artwork/v3/holidays/memorial-altered-source.png',
    aspectRatio: LANDSCAPE_ASPECT,
    verse: ["Soft lanterns keep their watch till night;","Small details drift in gentle light."],
    edits: [
      edit("blanket", "The ivory blanket turns sage-green.", "Easy", [322,323,471,378]),
      edit("lantern", "The lantern’s crescent becomes a star.", "Medium", [106,470,114,148]),
      edit("handle", "The blue vase loses its right handle.", "Hard", [1572,424,87,100]),
      edit("ribbon", "The wreath’s burgundy bow turns ivory.", "Very hard", [1122,708,286,218]),
      edit("stone", "The little stone loses its middle hole.", "Dreamlike", [861,652,27,27]),
    ],
  },
  {
    id: 'holiday-juneteenth', holiday: 'juneteenth', occasion: "Juneteenth",
    title: "The Gate of Morning",
    original: '/artwork/v3/holidays/juneteenth-original.png',
    altered: '/artwork/v3/holidays/juneteenth-altered-source.png',
    aspectRatio: LANDSCAPE_ASPECT,
    verse: ["The garden opens to the light;","Its little details change in flight."],
    edits: [
      edit("cloth", "The red cloth’s white star becomes a heart.", "Easy", [222,647,111,108]),
      edit("gate", "The gate’s sun medallion becomes a crescent.", "Medium", [698,42,109,105]),
      edit("stripe", "The blue jug loses its middle white stripe.", "Hard", [1474,687,182,35]),
      edit("pinwheel", "The pinwheel loses its lower-right petal.", "Very hard", [1037,633,54,61]),
      edit("brooch", "The mother’s gold flower brooch turns coral.", "Dreamlike", [733,534,48,53]),
    ],
  },
  {
    id: 'holiday-labor', holiday: 'labor', occasion: "Labor Day",
    title: "The Menders of the Moon",
    original: '/artwork/v3/holidays/labor-original.png',
    altered: '/artwork/v3/holidays/labor-altered-source.png',
    aspectRatio: LANDSCAPE_ASPECT,
    verse: ["The moon is mended seam by seam;","Small details wander through the dream."],
    edits: [
      edit("gear", "The wooden gear’s star-shaped hole becomes a crescent.", "Easy", [42,549,176,196]),
      edit("apron", "The beaver’s red apron turns teal.", "Medium", [360,355,287,249]),
      edit("handle", "The chest’s heart-shaped handle becomes a ring.", "Hard", [1448,636,92,99]),
      edit("stripe", "The mallet loses its left dark stripe.", "Very hard", [1142,724,64,134]),
      { ...edit("knob", "The kettle’s round knob becomes a star.", "Dreamlike", [548,657,42,45]), source: '/artwork/v3/holidays/labor-correction.png' },
    ],
  },
  {
    id: 'holiday-october-observance', holiday: 'october-observance', occasion: "Indigenous Peoples’ Day / Columbus Day",
    title: "The Valley in the Cedar",
    original: '/artwork/v3/holidays/october-observance-original.png',
    altered: '/artwork/v3/holidays/october-observance-altered-source.png',
    aspectRatio: LANDSCAPE_ASPECT,
    verse: ["An ancient cedar cradles streams;","Its quiet details shift in dreams."],
    edits: [
      edit("moon", "The golden moon turns silver-blue.", "Easy", [157,14,174,170]),
      edit("leaf", "The raven’s red leaf turns golden yellow.", "Medium", [1122,116,78,75]),
      edit("drop", "The maple leaf loses its uppermost dew drop.", "Hard", [1133,704,47,45]),
      edit("stone", "The stone’s heart-shaped opening becomes round.", "Very hard", [1353,501,196,193]),
      edit("petal", "The upper cream flower loses its bottom petal.", "Dreamlike", [113,578,39,53]),
    ],
  },
  {
    id: 'holiday-veterans', holiday: 'veterans', occasion: "Veterans Day",
    title: "The Light That Waited",
    original: '/artwork/v3/holidays/veterans-original.png',
    altered: '/artwork/v3/holidays/veterans-altered-source.png',
    aspectRatio: LANDSCAPE_ASPECT,
    verse: ["A lantern warms the path back home;","Through quiet dreams, small details roam."],
    edits: [
      edit("lantern", "The porch lantern’s crescent becomes a star.", "Easy", [1418,209,97,111]),
      edit("patch", "The suitcase’s green patch turns burgundy.", "Medium", [477,628,79,89]),
      edit("brooch", "The bear’s star brooch becomes a crescent.", "Hard", [714,290,52,58]),
      edit("handle", "The teacup’s blue handle turns red.", "Very hard", [1471,519,50,69]),
      edit("button", "The coat loses its lower gold button.", "Dreamlike", [730,462,35,36]),
    ],
  },
]
