// Original, spoiler-free rhyming verses keyed to published artwork IDs.
// Keep them brief and suggest a shifting dream without identifying an answer.
// The landing page supplies quotation marks; sentence count is not restricted.
export const dreamVerses: Readonly<Record<string, readonly [string, string]>> = {
  'dream-001': ["The orchard keeps its clocks asleep;", "Look twice—what did the branches keep?"],
  'dream-002': ["The seamstress tucks the rain in every seam;", "One blink unpicks the edges of the dream."],
  'dream-003': ["A pillow hides a midnight train;", "Look twice—the dream has changed its lane."],
  'dream-004': ["The ocean whispers through a door;", "Look back—is this the same old shore?"],
  'dream-005': ["A wandering house forgets its name;", "It comes back home, but not the same."],
  'dream-006': ["The sky unbuttons, seam by seam;", "What slips away between each dream?"],
  'dream-007': ["A garden whale sails out of sight;", "Its dream grows stranger in the night."],
  'dream-008': ["A pocket keeps a world of snow;", "Look twice—is this the world you know?"],
  'dream-009': ["Umbrellas hum a sweet refrain;", "A different tune slips through the rain."],
  'dream-010': ["Behind the glass, a garden grows;", "What changed? The sleeping greenhouse knows."],
  'dream-011': ["The tide turns pages on the sand;", "The tale comes back in altered hand."],
  'dream-012': ["The tailor hems the fading light;", "A different dream comes dressed tonight."],
  'dream-013': ["A berry beacon sweeps the bay;", "Some little thing has slipped away."],
  'dream-014': ["Balloons drift off without a sound;", "What secret did they leave aground?"],
  'dream-015': ["The moon hangs washing in the sky;", "What changed while clouds went drifting by?"],
  'dream-016': ["A teapot pours a mountain stream;", "Its second cup is not the same dream."],
  'dream-017': ["A deer bears autumn through the gold;", "Look twice—the tale is not as told."],
  'dream-018': ["The stairs remember where they led;", "But now another dream lies ahead."],
  'dream-019': ["A kettle wanders through the trees;", "Its secrets shift upon the breeze."],
  'dream-020': ["Lost wings remember how to fly;", "But something shifts beneath their sky."],
  'dream-021': ["The baker kneads the evening glow;", "What changed beneath the dusting snow?"],
  'dream-022': ["A snail maps wonders in the night;", "Look twice—does every mark seem right?"],
  'dream-023': ["A pocket gathers silver rain;", "A little dream slips down the drain."],
  'dream-024': ["A fox folds wishes into flight;", "They land a little changed tonight."],
  'dream-025': ["The orchard plucks its sleeping strings;", "Look twice at what the silence brings."],
  'dream-026': ["A house beneath a hat stays small;", "Yet dreams have rearranged it all."],
  'dream-027': ["A penguin dreams of summer air;", "Look twice—was that small wonder there?"],
  'dream-028': ["A swan awaits the train of day;", "The dream takes one small thing away."],
  'dream-029': ["The fish swim softly through the room;", "Look twice—what changed beneath the gloom?"],
  'dream-030': ["A gardener plants a comet bright;", "The dream grows differently tonight."],
  'dream-031': ["The forest wears a lamplit glow;", "Its paths are not the paths you know."],
  'dream-032': ["An ocean nestles in a glove;", "What changed below? What changed above?"],
  'dream-033': ["A marmalade world rolls through space;", "One blink, and strangeness takes its place."],
  'dream-034': ["Umbrellas dream upon a lake;", "Look twice—what trick did slumber make?"],
  'dream-035': ["The final stair leans toward the sea;", "It is not quite as it should be."],
  'dream-036': ["A rabbit lays a feast to share;", "Look twice—was everything once there?"],
  'dream-037': ["A whale keeps stories in the deep;", "Their smallest details drift in sleep."],
  'dream-038': ["A mirror dreams among the sand;", "Look back upon a slightly altered land."],
  'dream-039': ["An apricot drifts past the moon;", "Look twice—the dream has changed its tune."],
  'dream-040': ["The weather wears its porcelain white;", "Yet something has been changed by night."],
  'dream-041': ["The clockmaker puts time to rest;", "What shifted in this drowsy nest?"],
  'dream-042': ["A window wanders far and wide;", "Look twice at what it keeps inside."],
  'dream-043': ["An otter rocks a lemon boat;", "A little doubt has come afloat."],
  'dream-044': ["The moths perform in borrowed light;", "The second act is not quite right."],
  'dream-045': ["A chair floats gently out of sight;", "It brings a different dream tonight."],
  'dream-046': ["A peach parade goes drifting by;", "What changed beneath that candied sky?"],
  'dream-047': ["An attic whale swims through the deep;", "What did the dreaming fail to keep?"],
  'dream-048': ["Horizons settle in a hand;", "Look twice upon this shifting land."],
  'dream-049': ["A berry post sends dreams by mail;", "The same address—a different tale."],
  'dream-050': ["A river winds through ivory keys;", "Its tune has changed by slow degrees."],
  'dream-051': ["An umbrella trails a pool of shade;", "What little swap has slumber made?"],
  'dream-052': ["A mouse tends starlight, row by row;", "Look twice at how the dream might grow."],
  'dream-053': ["A swan keeps silk in shades of blue;", "One blink has dressed the dream anew."],
  'dream-054': ["Lost socks become an island chain;", "What stayed behind? What crossed the main?"],
  'dream-055': ["A tortoise watches kites take flight;", "Look twice—this breeze feels not quite right."],
  'dream-056': ["A fox keeps lanterns in a row;", "What changed beneath their sleepy glow?"],
  'dream-057': ["A pillow opens on a door;", "Was this the room you saw before?"],
  'dream-058': ["The cherries ring a tender chime;", "Look twice—dreams change in borrowed time."],
  'dream-059': ["The library has feathered wings;", "Its pages shuffle little things."],
  'dream-060': ["A cupboard keeps a mountain high;", "One blink has let a secret by."],
  'dream-061': ["Beneath the carpet, waters creep;", "What did they borrow from your sleep?"],
  'dream-062': ["Umbrellas drift where sea-lights glow;", "Look back—is this the scene you know?"],
  'dream-063': ["A biscuit train goes rolling by;", "What changed beneath its crumb-filled sky?"],
  'dream-064': ["The keeper hums a feathered song;", "Look twice—does every note belong?"],
  'dream-065': ["A cloud curls softly in a shoe;", "Look back—the dream has wandered too."],
  'dream-066': ["A fruit-borne boat slips out of sight;", "Its voyage comes back changed tonight."],
  'dream-067': ["The stars lie down without a sound;", "Look twice—has dreaming turned things round?"],
  'dream-068': ["A hat holds colors out of view;", "One blink, and something slips askew."],
  'dream-069': ["A sunflower lifts the day to flight;", "Look twice—does everything seem right?"],
  'dream-070': ["An owl maps roads of silver light;", "But dreams redraw the paths at night."],
  'dream-071': ["A doorway dreams in mirrored blue;", "Look twice—what slipped between the two?"],
  'dream-072': ["A ruby circus starts its show;", "The second act is not the one you know."],
  'dream-073': ["The garden borrows eyes to see;", "What changed between the dream and me?"],
  'dream-074': ["A folded sky lies soft and deep;", "Its creases shift while dreamers sleep."],
  'dream-075': ["Small skiers cross a spoon of snow;", "Look twice—which little things did go?"],
  'dream-076': ["The moon rents velvet rooms by night;", "Look twice—the guest book is not quite right."],
  'dream-077': ["An hourglass shelters passing rain;", "Some moments leave a different stain."],
  'dream-078': ["A peach pit frames a starry show;", "Look back—which scene did dreaming sew?"],
  'dream-079': ["The branches pluck a woodland tune;", "Its echoes change beneath the moon."],
  'dream-080': ["A drawer keeps winters long ago;", "Look twice at what the dream lets show."],
  'dream-081': ["The shop repairs the roofs of rain;", "Look back—what did the dream retain?"],
  'dream-082': ["A shadow slips into its shoes;", "Look twice at what the dark might lose."],
  'dream-083': ["Above the pancakes, planets gleam;", "Look twice—things are not what they seem."],
  'dream-084': ["A heron keeps a house of glass;", "Its little secrets shift and pass."],
  'dream-085': ["Behind a coat, the moon lies low;", "Look twice at what the shadows show."],
  'dream-086': ["A pear-shaped playground floats on air;", "Look back—was that small wonder there?"],
  'dream-087': ["A portrait wanders from its frame;", "It settles back, but not the same."],
  'dream-088': ["A river stitches shores with light;", "A seam slips loose while out of sight."],
  'dream-089': ["A raspberry climbs toward the blue;", "What changed while it was out of view?"],
  'dream-090': ["A badger ferries dreams through gray;", "Not all return the selfsame way."],
  'dream-091': ["A ribbon leads beyond the room;", "What changed behind its hush of gloom?"],
  'dream-092': ["A waffle windmill turns the breeze;", "Its world has shifted by degrees."],
  'dream-093': ["A tailor folds a paper swan;", "Look twice—what lingered, what has gone?"],
  'dream-094': ["A ladder loosens into rain;", "Look back—what does the dream retain?"],
  'dream-095': ["A tuba pours a citrus tune;", "Its echo changes with the moon."],
  'dream-096': ["A lily holds the hours still;", "Yet dreams keep changing at their will."],
  'dream-097': ["The sea folds up its wandering blue;", "Look twice—what did it hide from you?"],
  'dream-098': ["A honey railway winds toward home;", "What changed while little dreams could roam?"],
  'dream-099': ["A diver dreams beneath the deep;", "What did the tide forget to keep?"],
  'dream-100': ["A sandal keeps a window bright;", "Look twice at what slipped out of sight."],
  'dream-101': ["A telephone puts leaves on hold;", "The tale comes back not quite as told."],
  'dream-102': ["A violin sails on the tide;", "What changed upon the other side?"],
  'dream-103': ["A sugared meadow blushes pink;", "Its little truths can change in a blink."],
  'dream-104': ["A doorway fills with feathers white;", "Look twice at what came loose tonight."],
  'dream-105': ["The seahorses go round in play;", "What changed when you glanced away?"],
  'dream-106': ["A honey bear floats soft and slow;", "Look back—is this the dream you know?"],
  'dream-107': ["A curtain keeps an ocean blue;", "Its folds conceal a different view."],
  'dream-108': ["A stag reads tales by velvet light;", "The words remember wrong tonight."],
  'dream-109': ["The rowers cross a kiwi green;", "Look twice—is this the selfsame scene?"],
  'dream-110': ["A sleeve conceals a hidden stair;", "Look back—was all of this once there?"],
  'dream-111': ["A bicycle collects the sky;", "What changed as little clouds rolled by?"],
  'dream-112': ["A lemon swing sails out of sight;", "It brings a stranger dream to light."],
  'dream-113': ["A mirror dreams beyond its frame;", "Look twice—its world is not the same."],
  'dream-114': ["The orchard glows with lantern light;", "What changed between a blink and night?"],
  'dream-115': ["A cherry moon hangs in the sky;", "The dream has changed—can you spot why?"],
  'dream-116': ["An umbrella waits beyond the hall;", "Does memory remember all?"],
  'dream-117': ["A fox walks trees of porcelain white;", "Look twice at what has changed tonight."],
  'dream-118': ["The melon boats go drifting slow;", "What did they take? What did they stow?"],
  'dream-119': ["A ribbon knot keeps rooms inside;", "Look twice—what does the dreaming hide?"],
  'dream-120': ["One lantern keeps the night aglow;", "What changed before the dreams could go?"],
}

export function verseForDream(id: string): readonly [string, string] {
  const verse = dreamVerses[id]
  if (!verse) throw new Error(`Missing dream verse: ${id}`)
  return verse
}
