// Original, spoiler-free couplets keyed to published artwork IDs, not the date.
// A day's verse therefore follows the same card in daily play and dev previews.
// Keep each poem to at most two sentences; the landing page adds quotation marks.
export const dreamVerses: Readonly<Record<string, readonly [string, string]>> = {
  'dream-001': ['The orchard keeps its hours asleep,', 'And dreams the time no clock can keep.'],
  'dream-002': ['A quiet needle stitches rain,', 'And sews the sky to sleep again.'],
  'dream-003': ['Beneath a pillow, railways gleam,', 'A midnight train runs through a dream.'],
  'dream-004': ['Beyond the door, the oceans roar,', 'Yet morning cannot find the shore.'],
  'dream-005': ['A restless house set out to roam,', 'And every road remembered home.'],
  'dream-006': ['The sky unfastens, seam by seam,', 'And lets the daylight spill a dream.'],
  'dream-007': ['A whale bears gardens through the deep,', 'Where drifting roots and roses sleep.'],
  'dream-008': ['A pocket holds the winter snow,', 'And keeps the paths we used to know.'],
  'dream-009': ['Umbrellas play a soft refrain,', 'An orchestra composed of rain.'],
  'dream-010': ['Behind the glass, a garden grows,', 'In soil no waking season knows.'],
  'dream-011': ['The tide turns pages on the sand,', 'Of stories written far from land.'],
  'dream-012': ['The tailor folds the fading light,', 'And dresses shadows for the night.'],
  'dream-013': ['A berry beacon lights the foam,', 'And calls the wandering dreamers home.'],
  'dream-014': ['Balloons depart without a sound,', 'With little dreams no string has bound.'],
  'dream-015': ['The moon hangs washing out to dry,', 'And leaves its dreams across the sky.'],
  'dream-016': ['A teapot hums beneath the steam,', 'Then pours a mountain from a dream.'],
  'dream-017': ['A deer bears autumn through the gold,', 'With tales the falling leaves once told.'],
  'dream-018': ['The stairs forget which way to go,', 'And dream of skies that lie below.'],
  'dream-019': ['A kettle wanders on the breeze,', 'And whistles softly past the trees.'],
  'dream-020': ['Lost wings remember how to fly,', 'Though walls have taken back the sky.'],
  'dream-021': ['The baker kneads the evening glow,', 'And warms the dusk like rising dough.'],
  'dream-022': ['A patient snail consults the night,', 'And finds a thousand paths of light.'],
  'dream-023': ['A pocket gathers passing rain,', 'To let a lost day bloom again.'],
  'dream-024': ['A fox folds moonlight into flight,', 'And sends a paper wish through night.'],
  'dream-025': ['The orchard hums a tune of strings,', 'And every sleeping branch now sings.'],
  'dream-026': ['Beneath a hat, a house stays small,', 'Yet holds a sky beyond its wall.'],
  'dream-027': ['A penguin dreams of summer air,', 'And leaves the winter waiting there.'],
  'dream-028': ['A swan awaits the train of day,', 'While sleeping waters drift away.'],
  'dream-029': ['Slow fish go sailing through the room,', 'Like quiet thoughts that learn to bloom.'],
  'dream-030': ['A gardener tends the comet light,', 'And sows a little more of night.'],
  'dream-031': ['The forest wears a shaded glow,', 'Where lamplit dreams take root and grow.'],
  'dream-032': ['A glove holds oceans in its palm,', 'And rocks the restless waves to calm.'],
  'dream-033': ['A marmalade world rolls through space,', 'With morning warmth upon its face.'],
  'dream-034': ['Umbrellas dream upon the lake,', 'Of all the journeys rain might take.'],
  'dream-035': ['The final stair leans toward the sea,', 'And wonders where the next might be.'],
  'dream-036': ['A rabbit lays a feast on air,', 'For passing clouds to stop and share.'],
  'dream-037': ['A whale keeps stories in the deep,', 'And marks the place where readers sleep.'],
  'dream-038': ['A mirror waits among the sand,', 'Reflecting some forgotten land.'],
  'dream-039': ['An apricot takes wing at noon,', 'And sails toward a sleepy moon.'],
  'dream-040': ['The weather dreams in porcelain white,', 'Too delicate to hold till night.'],
  'dream-041': ['The clockmaker has built a nest,', 'Where weary little hours can rest.'],
  'dream-042': ['A window wanders far and wide,', 'To see what waits on either side.'],
  'dream-043': ['An otter rows a lemon boat,', 'With all its waking cares afloat.'],
  'dream-044': ['The moths perform in borrowed light,', 'And take their bows before the night.'],
  'dream-045': ['A chair floats high above the rain,', 'And waits for you to dream again.'],
  'dream-046': ['A peach parade goes drifting by,', 'With sweet umbrellas for the sky.'],
  'dream-047': ['An attic whale swims slow and deep,', 'Through all the things a house might keep.'],
  'dream-048': ['Horizons nestle in a hand,', 'Too far to touch, too near to land.'],
  'dream-049': ['A berry post sends letters through,', 'To places only dreamers knew.'],
  'dream-050': ['A river winds through ivory keys,', 'And plays its song to distant seas.'],
  'dream-051': ['An umbrella trails a shade,', 'Along a road the dreaming made.'],
  'dream-052': ['A little mouse tends stars at night,', 'And waters every seed of light.'],
  'dream-053': ['A swan keeps garments out of view,', 'For all the lives it never knew.'],
  'dream-054': ['Lost socks become an island chain,', 'Where absent footsteps meet again.'],
  'dream-055': ['A tortoise watches kites take flight,', 'And travels slowly through their light.'],
  'dream-056': ['A fox keeps lanterns in a row,', 'To guide the dreams too shy to glow.'],
  'dream-057': ['A pillow opens on a door,', 'To somewhere you have dreamed before.'],
  'dream-058': ['The cherries ring a tender chime,', 'That ripens on the boughs of time.'],
  'dream-059': ['A library of feathered things,', 'Keeps all the tales the night wind sings.'],
  'dream-060': ['A cupboard keeps a mountain high,', 'Too tall for walls, too small for sky.'],
  'dream-061': ['Beneath the carpet, waters sweep,', 'And carry household dreams to sleep.'],
  'dream-062': ['Umbrellas drift where jellyfish glow,', 'Through quiet tides that dreamers know.'],
  'dream-063': ['A biscuit train goes rolling by,', 'With crumbs of morning in the sky.'],
  'dream-064': ['All night the keeper tends a song,', 'For birds that never stayed for long.'],
  'dream-065': ['A cloud curls softly in a shoe,', 'And dreams of roads it never knew.'],
  'dream-066': ['A curved gondola slips from sight,', 'A fruit-borne voyage into night.'],
  'dream-067': ['The stars lie down without a sound,', 'And dream the sky the other way round.'],
  'dream-068': ['A hat holds colors after rain,', 'To paint the sleeping world again.'],
  'dream-069': ['A sunflower turns against the blue,', 'And lifts the day to somewhere new.'],
  'dream-070': ['An owl maps paths across the night,', 'By roads too soft for waking sight.'],
  'dream-071': ['A doorway dreams in mirrored blue,', 'Of all the skies that might pass through.'],
  'dream-072': ['A circus blooms in ruby glow,', 'Where little dreams put on a show.'],
  'dream-073': ['The garden borrows eyes to see,', 'A world as strange as it can be.'],
  'dream-074': ['A folded sky lies soft and deep,', 'With far horizons tucked to sleep.'],
  'dream-075': ['Small skiers glide on spoonfuls of snow,', 'To valleys only teacups know.'],
  'dream-076': ['The velvet moon lets rooms by night,', 'For dreams too tired to take their flight.'],
  'dream-077': ['An hourglass shelters passing rain,', 'While moments wander through again.'],
  'dream-078': ['A peach pit holds the stars in sight,', 'A tiny theatre for the night.'],
  'dream-079': ['The branches pluck a woodland tune,', 'And hum it softly to the moon.'],
  'dream-080': ['A drawer keeps snow from long ago,', 'And all the tracks we used to know.'],
  'dream-081': ['The shop repairs the roofs of rain,', 'So little storms can roam again.'],
  'dream-082': ['A shadow slips into its shoes,', 'And walks the roads that dreamers choose.'],
  'dream-083': ['Above the pancakes, planets gleam,', 'A breakfast at the edge of dream.'],
  'dream-084': ['A heron keeps a house of glass,', 'And watches quiet seasons pass.'],
  'dream-085': ['Behind a coat, the moon lies low,', 'And warms the dark with borrowed glow.'],
  'dream-086': ['A playground curves through pear-sweet air,', 'With room for every dream to share.'],
  'dream-087': ['A portrait dreams beyond its frame,', 'Of places with no waking name.'],
  'dream-088': ['The river threads the land with light,', 'And stitches shore to shore at night.'],
  'dream-089': ['A raspberry climbs past the blue,', 'To taste the stars it never knew.'],
  'dream-090': ['A badger ferries dreams through gray,', 'To shores the fog has tucked away.'],
  'dream-091': ['A ribbon leads beyond the room,', 'To where forgotten wishes bloom.'],
  'dream-092': ['A waffle windmill turns the breeze,', 'And grinds the dawn with gentle ease.'],
  'dream-093': ['A tailor folds a paper swan,', 'To wear the dreams of days long gone.'],
  'dream-094': ['A ladder loosens into rain,', 'And climbs the sky as mist again.'],
  'dream-095': ['A tuba pours a citrus tune,', 'That rolls like sunshine toward the moon.'],
  'dream-096': ['A lily holds the hours still,', 'While time drifts on beyond its will.'],
  'dream-097': ['The sea folds up its wandering blue,', 'And saves a little wave for you.'],
  'dream-098': ['A railway threads a honeyed comb,', 'And carries drowsy travelers home.'],
  'dream-099': ['A diver shelters in the deep,', 'Beneath a canopy of sleep.'],
  'dream-100': ['A sandal keeps a window bright,', 'For footsteps wandering out of sight.'],
  'dream-101': ['A telephone puts leaves on hold,', 'And whispers tales the forest told.'],
  'dream-102': ['A violin sails on a silver tide,', 'With moonlit music for its guide.'],
  'dream-103': ['A meadow dreams in sugared pink,', 'Too sweet to vanish when you blink.'],
  'dream-104': ['The doorway fills with feathers white,', 'Like quiet letters sent by night.'],
  'dream-105': ['The seahorses go round in play,', 'And turn the tide the other way.'],
  'dream-106': ['A honey bear floats soft and slow,', 'Above the waking world below.'],
  'dream-107': ['A curtain holds small oceans blue,', 'And lets a little daylight through.'],
  'dream-108': ['A stag reads softly through the night,', 'In velvet rooms of borrowed light.'],
  'dream-109': ['The rowers glide through kiwi green,', 'Toward a shore no map has seen.'],
  'dream-110': ['A staircase hides inside a sleeve,', 'And leads to things we half believe.'],
  'dream-111': ['A bicycle collects the sky,', 'And pedals little cloud-dreams by.'],
  'dream-112': ['A lemon swing sails out of sight,', 'And rocks the day toward dreams of night.'],
  'dream-113': ['The mirror dreams of being held,', 'By hands that waking light dispelled.'],
  'dream-114': ['The orchard glows with lantern light,', 'And sings its branches into night.'],
  'dream-115': ['A cherry moon hangs warm and high,', 'A little slice of dreaming pie.'],
  'dream-116': ['An umbrella waits beyond the hall,', 'For rain that waking cannot call.'],
  'dream-117': ['A fox treads softly through the white,', 'Where porcelain trees hold cups of light.'],
  'dream-118': ['The melon boats go drifting slow,', 'Where summer rivers dream and flow.'],
  'dream-119': ['A ribbon knot keeps rooms inside,', 'Where little folded wishes hide.'],
  'dream-120': ['One lantern keeps the night aglow,', 'While morning waits for dreams to go.'],
}

export function verseForDream(id: string): readonly [string, string] {
  const verse = dreamVerses[id]
  if (!verse) throw new Error(`Missing dream verse: ${id}`)
  return verse
}
