// Offline metadata import and verbatim master copies; never repaint/resize assets.
import { readFileSync, writeFileSync, copyFileSync, existsSync, mkdirSync, readdirSync } from 'node:fs'
import { resolve, join, basename } from 'node:path'
import { createHash } from 'node:crypto'
import assert from 'node:assert/strict'

const root = resolve(import.meta.dirname, '..')
assert.ok(process.argv[2], 'Pass the reviewed revisit directory')
const source = resolve(process.argv[2])
const read = file => JSON.parse(readFileSync(file, 'utf8').replace(/^\uFEFF/, ''))
const prefix = '/artwork/v3/collection-revisit-v1/'
const target = join(root, 'public', prefix)
const assets = new Map(), cards = [], reviews = [], replacements = {}
const hash = bytes => createHash('sha256').update(bytes).digest('hex')
function asset(file) {
  const bytes = readFileSync(file), name = basename(file), destination = join(target, name)
  assert.equal(bytes.subarray(1, 4).toString(), 'PNG')
  const width = bytes.readUInt32BE(16), height = bytes.readUInt32BE(20)
  assert.ok(Math.abs(width - 1672) <= 1 && Math.abs(height - 941) <= 1)
  if (existsSync(destination)) assert.equal(hash(readFileSync(destination)), hash(bytes), 'Never overwrite pixels')
  else { mkdirSync(target, { recursive: true }); copyFileSync(file, destination) }
  assets.set(name, { file: name, sha256: hash(bytes), width, height, bytes: bytes.length })
  return prefix + name
}
for (const filename of readdirSync(source).filter(f => /^revisit-dream-.+\.json$/.test(f)).sort()) {
  const plan = read(join(source, filename))
  assert.match(plan.status, /^visual QA passed/)
  assert.equal(plan.qa.fullComposite, 'passed')
  assert.equal(plan.qa.fiveAnswerCrops, 'passed')
  assert.ok(existsSync(join(source, plan.qa.fullScreenshot)))
  assert.ok(existsSync(join(source, plan.qa.cropScreenshot)))
  assert.equal(plan.edits.length, 5)
  assert.equal(new Set(plan.edits.map(e => e.id)).size, 5)
  const edits = plan.edits.map(e => {
    const [x,y,w,h] = e.box
    assert.ok(e.box.every(Number.isFinite) && x >= 0 && y >= 0 && w > 0 && h > 0 && x+w <= 1672 && y+h <= 941)
    return { id:e.id, label:e.label, difficulty:e.difficulty,
      box:{left:x/1672,top:y/941,width:w/1672,height:h/941}, edgeFade:e.edgeFade ?? 6,
      ...(e.source ? {source:asset(e.source)} : {}), ...(e.maskPath ? {maskPath:e.maskPath} : {}) }
  })
  cards.push({id:plan.id,title:plan.title,original:asset(plan.original),altered:asset(plan.altered),aspectRatio:1672/941,edits})
  replacements[plan.previousId] = plan.id
  reviews.push(plan)
}
assert.equal(cards.length, 37)
writeFileSync(join(root,'src/v3/revisitedCollection.generated.ts'), "// Generated by scripts/importRevisitedCollection.mjs; preserve published versions.\nimport type { LandscapeDream } from '../v2/landscapeCollection.ts'\nexport const revisitedCollection: readonly LandscapeDream[] = [\n"+cards.map(c=>'  '+JSON.stringify(c)+',').join('\n')+'\n]\nexport const revisitIds: Readonly<Record<string,string>> = '+JSON.stringify(replacements,null,2)+'\n')
writeFileSync(join(root,'docs/artwork/REVISIT_PROVENANCE.json'),JSON.stringify({generator:'built-in imagegen',scope:'37 owner-selected redesigned originals and 185 visually checked changes; previous versions preserved',cards:reviews,assets:[...assets.values()],originalPrompts:['refined-prompts.json','refined-remaining-prompts.json'].map(file=>({file,data:read(join(source,file))}))},null,2)+'\n')
console.log(JSON.stringify({cards:cards.length,answers:cards.length*5,assets:assets.size}))
