// Offline, mechanical import of the owner-approved 121–365 review workspace.
// No raster edits: copy selected masters verbatim and generate typed metadata.
import { readFileSync, writeFileSync, copyFileSync, existsSync, mkdirSync } from 'node:fs'
import { resolve, dirname, basename, join } from 'node:path'
import { createHash } from 'node:crypto'
import assert from 'node:assert/strict'

const root = resolve(import.meta.dirname, '..')
const source = resolve(process.argv[2] || '')
if (!process.argv[2]) throw new Error('Pass the expansion-playable-121-365 review directory')
const read = path => JSON.parse(readFileSync(path, 'utf8').replace(/^\uFEFF/, ''))
const originals = read(join(source, 'originals-manifest.json')).cards
const prefix = '/artwork/v3/collection-year-v1/'
const assets = new Map(), cards = [], reviews = [], verses = {}
const hash = data => createHash('sha256').update(data).digest('hex')
function asset(path) {
  const bytes = readFileSync(path), file = basename(path), target = join(root, 'public', prefix, file)
  assert.equal(bytes.subarray(1, 4).toString(), 'PNG', path)
  const width = bytes.readUInt32BE(16), height = bytes.readUInt32BE(20)
  assert.ok(Math.abs(width - 1672) <= 1 && Math.abs(height - 941) <= 1, path)
  if (existsSync(target)) assert.equal(hash(readFileSync(target)), hash(bytes), 'Never overwrite different pixels')
  else { mkdirSync(dirname(target), { recursive: true }); copyFileSync(path, target) }
  assets.set(file, { file, sha256: hash(bytes), bytes: bytes.length, width, height })
  return prefix + file
}
for (let number = 121; number <= 365; number++) {
  const id = 'dream-' + number, plan = read(join(source, id + '.json'))
  assert.match(plan.status, /^visual QA passed/, id)
  assert.ok(['pass', 'passed', true].includes(plan.qa.fullComposite) || (plan.qa.status === 'passed' && plan.qa.checks.includes('Full composited artwork inspected.')), id)
  assert.ok(plan.qa.fiveAnswerCrops === 'passed' || plan.qa.allFiveAnswerCrops === 'pass' || plan.qa.pairedAnswerCrops === 5 || plan.qa.answerCrops === 5 || (plan.qa.status === 'passed' && plan.qa.checks.includes('All five original/altered paired answer crops inspected.')), id)
  assert.equal(plan.edits.length, 5, id)
  assert.equal(new Set(plan.edits.map(e => e.id)).size, 5, id)
  const frozen = originals.find(card => card.id === id)
  assert.equal(hash(readFileSync(plan.original)), frozen.sha256, id + ' approved original')
  const edits = plan.edits.map(edit => {
    const b = edit.box
    assert.equal(b.length, 4, id + '/' + edit.id)
    assert.ok(b.every(Number.isFinite) && b[0] >= 0 && b[1] >= 0 && b[2] > 0 && b[3] > 0 && b[0]+b[2] <= 1672 && b[1]+b[3] <= 941, id + '/' + edit.id)
    return { id: edit.id, label: edit.label, difficulty: edit.difficulty,
      box: { left: b[0]/1672, top: b[1]/941, width: b[2]/1672, height: b[3]/941 },
      edgeFade: edit.edgeFade ?? 2, ...(edit.maskPath ? { maskPath: edit.maskPath } : {}),
      ...(edit.source ? { source: asset(edit.source) } : {}) }
  })
  cards.push({ id: 'painted-' + id, title: plan.title, original: asset(plan.original),
    altered: asset(plan.altered), aspectRatio: 1672/941, edits })
  const lines = Array.isArray(plan.verse) ? plan.verse : plan.verse.split('\n')
  assert.equal(lines.length, 2, id + ' verse')
  verses[id] = lines
  const provenance = join(dirname(plan.original), id + '-provenance.json')
  assert.ok(existsSync(provenance), id + ' original provenance')
  reviews.push({ ...plan, originalProvenance: read(provenance) })
}
assert.equal(cards.length, 245)
writeFileSync(join(root, 'src/v3/yearExpansion.generated.ts'), "// Generated by scripts/importYearExpansion.mjs from reviewed plans.\nimport type { LandscapeDream } from '../v2/landscapeCollection.ts'\nexport const yearExpansion: readonly LandscapeDream[] = [\n" + cards.map(card => '  ' + JSON.stringify(card) + ',').join('\n') + '\n]\nexport const yearVerses: Readonly<Record<string, readonly [string, string]>> = ' + JSON.stringify(verses, null, 2) + '\n')
writeFileSync(join(root, 'docs/artwork/YEAR_EXPANSION_PROVENANCE.json'), JSON.stringify({ generator: 'built-in imagegen', scope: '245 approved originals and exactly five clipped edits each; rejected teapot is backup-only', cards: reviews, assets: [...assets.values()] }, null, 2) + '\n')
console.log(JSON.stringify({ cards: cards.length, assets: assets.size, answers: cards.length * 5, bytes: [...assets.values()].reduce((sum, a) => sum + a.bytes, 0) }))
