// Generated by scripts/create-placeholder-artwork.mjs.
import type { Card } from '../game/types.ts'

export const cards: readonly Card[] = [
  {
    "id": "card-001",
    "artwork": "/artwork/card-001.svg",
    "description": "1 open doorways stand above water, with small moons beyond them."
  },
  {
    "id": "card-002",
    "artwork": "/artwork/card-002.svg",
    "description": "2 open doorways stand above water, with small moons beyond them."
  },
  {
    "id": "card-003",
    "artwork": "/artwork/card-003.svg",
    "description": "3 open doorways stand above water, with small moons beyond them."
  },
  {
    "id": "card-004",
    "artwork": "/artwork/card-004.svg",
    "description": "4 open doorways stand above water, with small moons beyond them."
  },
  {
    "id": "card-005",
    "artwork": "/artwork/card-005.svg",
    "description": "5 open doorways stand above water, with small moons beyond them."
  },
  {
    "id": "card-006",
    "artwork": "/artwork/card-006.svg",
    "description": "6 open doorways stand above water, with small moons beyond them."
  },
  {
    "id": "card-007",
    "artwork": "/artwork/card-007.svg",
    "description": "A small house rests on 2 slender stilts, with a ribbon of water passing through its window."
  },
  {
    "id": "card-008",
    "artwork": "/artwork/card-008.svg",
    "description": "A small house rests on 3 slender stilts, with a ribbon of water passing through its window."
  },
  {
    "id": "card-009",
    "artwork": "/artwork/card-009.svg",
    "description": "A small house rests on 4 slender stilts, with a ribbon of water passing through its window."
  },
  {
    "id": "card-010",
    "artwork": "/artwork/card-010.svg",
    "description": "A small house rests on 5 slender stilts, with a ribbon of water passing through its window."
  },
  {
    "id": "card-011",
    "artwork": "/artwork/card-011.svg",
    "description": "A small house rests on 6 slender stilts, with a ribbon of water passing through its window."
  },
  {
    "id": "card-012",
    "artwork": "/artwork/card-012.svg",
    "description": "A small house rests on 7 slender stilts, with a ribbon of water passing through its window."
  },
  {
    "id": "card-013",
    "artwork": "/artwork/card-013.svg",
    "description": "A stairway with 5 steps rises toward a suspended ring, above a low bank of clouds."
  },
  {
    "id": "card-014",
    "artwork": "/artwork/card-014.svg",
    "description": "A stairway with 6 steps rises toward a suspended ring, above a low bank of clouds."
  },
  {
    "id": "card-015",
    "artwork": "/artwork/card-015.svg",
    "description": "A stairway with 7 steps rises toward a suspended ring, above a low bank of clouds."
  },
  {
    "id": "card-016",
    "artwork": "/artwork/card-016.svg",
    "description": "A stairway with 8 steps rises toward a suspended ring, above a low bank of clouds."
  },
  {
    "id": "card-017",
    "artwork": "/artwork/card-017.svg",
    "description": "A stairway with 9 steps rises toward a suspended ring, above a low bank of clouds."
  },
  {
    "id": "card-018",
    "artwork": "/artwork/card-018.svg",
    "description": "A stairway with 10 steps rises toward a suspended ring, above a low bank of clouds."
  },
  {
    "id": "card-019",
    "artwork": "/artwork/card-019.svg",
    "description": "A glass bowl holds 1 tiny islands, with a crescent hanging inside the glass."
  },
  {
    "id": "card-020",
    "artwork": "/artwork/card-020.svg",
    "description": "A glass bowl holds 2 tiny islands, with a crescent hanging inside the glass."
  },
  {
    "id": "card-021",
    "artwork": "/artwork/card-021.svg",
    "description": "A glass bowl holds 3 tiny islands, with a crescent hanging inside the glass."
  },
  {
    "id": "card-022",
    "artwork": "/artwork/card-022.svg",
    "description": "A glass bowl holds 4 tiny islands, with a crescent hanging inside the glass."
  },
  {
    "id": "card-023",
    "artwork": "/artwork/card-023.svg",
    "description": "A glass bowl holds 5 tiny islands, with a crescent hanging inside the glass."
  },
  {
    "id": "card-024",
    "artwork": "/artwork/card-024.svg",
    "description": "A glass bowl holds 6 tiny islands, with a crescent hanging inside the glass."
  },
  {
    "id": "card-025",
    "artwork": "/artwork/card-025.svg",
    "description": "A whale floats above 1 suspended lanterns, its tail pointing into the night."
  },
  {
    "id": "card-026",
    "artwork": "/artwork/card-026.svg",
    "description": "A whale floats above 2 suspended lanterns, its tail pointing into the night."
  },
  {
    "id": "card-027",
    "artwork": "/artwork/card-027.svg",
    "description": "A whale floats above 3 suspended lanterns, its tail pointing into the night."
  },
  {
    "id": "card-028",
    "artwork": "/artwork/card-028.svg",
    "description": "A whale floats above 4 suspended lanterns, its tail pointing into the night."
  },
  {
    "id": "card-029",
    "artwork": "/artwork/card-029.svg",
    "description": "A whale floats above 5 suspended lanterns, its tail pointing into the night."
  },
  {
    "id": "card-030",
    "artwork": "/artwork/card-030.svg",
    "description": "A whale floats above 6 suspended lanterns, its tail pointing into the night."
  },
  {
    "id": "card-031",
    "artwork": "/artwork/card-031.svg",
    "description": "1 paper boats drift in a vertical ribbon of water between two distant hills."
  },
  {
    "id": "card-032",
    "artwork": "/artwork/card-032.svg",
    "description": "2 paper boats drift in a vertical ribbon of water between two distant hills."
  },
  {
    "id": "card-033",
    "artwork": "/artwork/card-033.svg",
    "description": "3 paper boats drift in a vertical ribbon of water between two distant hills."
  },
  {
    "id": "card-034",
    "artwork": "/artwork/card-034.svg",
    "description": "4 paper boats drift in a vertical ribbon of water between two distant hills."
  },
  {
    "id": "card-035",
    "artwork": "/artwork/card-035.svg",
    "description": "5 paper boats drift in a vertical ribbon of water between two distant hills."
  },
  {
    "id": "card-036",
    "artwork": "/artwork/card-036.svg",
    "description": "6 paper boats drift in a vertical ribbon of water between two distant hills."
  },
  {
    "id": "card-037",
    "artwork": "/artwork/card-037.svg",
    "description": "An upside-down tree carries 3 round stones where its branches meet the sky."
  },
  {
    "id": "card-038",
    "artwork": "/artwork/card-038.svg",
    "description": "An upside-down tree carries 4 round stones where its branches meet the sky."
  },
  {
    "id": "card-039",
    "artwork": "/artwork/card-039.svg",
    "description": "An upside-down tree carries 5 round stones where its branches meet the sky."
  },
  {
    "id": "card-040",
    "artwork": "/artwork/card-040.svg",
    "description": "An upside-down tree carries 6 round stones where its branches meet the sky."
  },
  {
    "id": "card-041",
    "artwork": "/artwork/card-041.svg",
    "description": "An upside-down tree carries 7 round stones where its branches meet the sky."
  },
  {
    "id": "card-042",
    "artwork": "/artwork/card-042.svg",
    "description": "An upside-down tree carries 8 round stones where its branches meet the sky."
  },
  {
    "id": "card-043",
    "artwork": "/artwork/card-043.svg",
    "description": "A chair with 2 long shadows stands on a narrow floating platform."
  },
  {
    "id": "card-044",
    "artwork": "/artwork/card-044.svg",
    "description": "A chair with 3 long shadows stands on a narrow floating platform."
  },
  {
    "id": "card-045",
    "artwork": "/artwork/card-045.svg",
    "description": "A chair with 4 long shadows stands on a narrow floating platform."
  },
  {
    "id": "card-046",
    "artwork": "/artwork/card-046.svg",
    "description": "A chair with 5 long shadows stands on a narrow floating platform."
  },
  {
    "id": "card-047",
    "artwork": "/artwork/card-047.svg",
    "description": "A chair with 6 long shadows stands on a narrow floating platform."
  },
  {
    "id": "card-048",
    "artwork": "/artwork/card-048.svg",
    "description": "A chair with 7 long shadows stands on a narrow floating platform."
  },
  {
    "id": "card-049",
    "artwork": "/artwork/card-049.svg",
    "description": "An umbrella shelters 1 small stars while rain rises from the ground around it."
  },
  {
    "id": "card-050",
    "artwork": "/artwork/card-050.svg",
    "description": "An umbrella shelters 2 small stars while rain rises from the ground around it."
  },
  {
    "id": "card-051",
    "artwork": "/artwork/card-051.svg",
    "description": "An umbrella shelters 3 small stars while rain rises from the ground around it."
  },
  {
    "id": "card-052",
    "artwork": "/artwork/card-052.svg",
    "description": "An umbrella shelters 4 small stars while rain rises from the ground around it."
  },
  {
    "id": "card-053",
    "artwork": "/artwork/card-053.svg",
    "description": "An umbrella shelters 5 small stars while rain rises from the ground around it."
  },
  {
    "id": "card-054",
    "artwork": "/artwork/card-054.svg",
    "description": "An umbrella shelters 6 small stars while rain rises from the ground around it."
  },
  {
    "id": "card-055",
    "artwork": "/artwork/card-055.svg",
    "description": "A hanging swing holds 1 pale spheres above a mountain-shaped shadow."
  },
  {
    "id": "card-056",
    "artwork": "/artwork/card-056.svg",
    "description": "A hanging swing holds 2 pale spheres above a mountain-shaped shadow."
  },
  {
    "id": "card-057",
    "artwork": "/artwork/card-057.svg",
    "description": "A hanging swing holds 3 pale spheres above a mountain-shaped shadow."
  },
  {
    "id": "card-058",
    "artwork": "/artwork/card-058.svg",
    "description": "A hanging swing holds 4 pale spheres above a mountain-shaped shadow."
  },
  {
    "id": "card-059",
    "artwork": "/artwork/card-059.svg",
    "description": "A hanging swing holds 5 pale spheres above a mountain-shaped shadow."
  },
  {
    "id": "card-060",
    "artwork": "/artwork/card-060.svg",
    "description": "A hanging swing holds 6 pale spheres above a mountain-shaped shadow."
  }
]
